### ISSUE TITLE
关于 部署离线 opt 环境下载地址，也不知道该在哪反馈，就这好了

### ISSUE THREAD

**Issue by wsltshh** [hiboyhiboy/opt-file#3]
我想在主路由上只开 部署离线 opt 环境下载地址 给副路由用，主路由不开 自定义 opt 环境下载地址
主路由带储存，副路由是下载到内存，所以希望可以不同时开两个选项

**Comment by Jasam-You** [comment]
自定义 opt 环境下载地址 里的内容你保持默认，效果就跟不开是一样的，打开也无碍

**Comment by wsltshh** [comment]
> 自定义opt环境下载地址里的内容你保持默认，效果就跟不开是一样的，打开也无阻碍

当初内容好像是本地连接来着？也没琢磨，刚才又看看，也对啊。写 https://opt.cn2qq.com 就行了。谢谢
