### ISSUE TITLE
shadowsocks高级启动参数添加--no-delay后生成配置文件错误

### ISSUE THREAD

**Issue by KyonLi** [hiboyhiboy/opt-file#4]
![image](https://user-images.githubusercontent.com/7446107/30520228-0d575d28-9bdc-11e7-93f4-86a68aa9f507.png)
![image](https://user-images.githubusercontent.com/7446107/30520223-f8b83fcc-9bdb-11e7-81b8-5cb820b6453a.png)

填到了"obfs": "-delay"

**Comment by hiboyhiboy** [comment]
更新脚本修复

**Comment by KyonLi** [comment]
谢谢
